import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type TLayoutProps = {
  children: React.ReactNode;
}

export default function RootLayout({ children }: TLayoutProps) {
  return (
    <html lang="ru">
      <head>
        <title>PET PROJECT</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
